### ISSUE TITLE
请问你有没有网卡偶尔断开的问题？

### ISSUE THREAD

**Issue by leeyonwang** [jianyun8023/MSI-MAG-B560M-i5-11500#1]
2.5G网卡。我是另买了一个b156b的usb网卡插在我的软路由上。能联网，但是使用过程中总是随机断开，然后马上重连。没有固定时间，就是时不时来一下。请问你有这个情况吗？

**Comment by jianyun8023** [comment]
我长时间用在了1g速率模式是稳定。2.5g模式短时间用过，不确定有没有问题。我周末可以连2.5g的交换机测试下是否问题

**Comment by jianyun8023** [comment]
@leeyonwang 跑了一个小时，没有问题。连接的2.5G交换机
![image](https://user-images.githubusercontent.com/18240360/160424234-640bbd9f-b859-4e68-b192-d18d01402f00.jpeg)

并且iperf3测速可以跑到2.4G带宽

**Comment by leeyonwang** [comment]
明白了 你开了巨型帧了吧

**Comment by jianyun8023** [comment]
> 明白了 你开了巨型帧了吧

并没有，默认1500

**Comment by leeyonwang** [comment]
允许我挖个坟，更新一下。
确实是软路由的问题，之前用usb 8156b网卡弄得2.5g网口。换了4口8125 pcie网卡，现在稳如狗。

**Comment by jianyun8023** [comment]
> 允许我挖个坟，更新一下。 确实是软路由的问题，之前用usb 8156b网卡弄得2.5g网口。换了4口8125 pcie网卡，现在稳如狗。

软路由用的ikuai吗？ikuai的几个Lan桥接在一起，是同速率的还ok。如果不同速率，速率不稳且容易协商到百兆。
我的软路由ikuai + usb 8156b, 再连接到2.5G交换机, 通过交换机分享网络。
