### ISSUE TITLE
大佬，我跟你一样的主板，能用这套EFI不

### ISSUE THREAD

**Issue by hoowhoami** [jianyun8023/MSI-MAG-B560M-i5-11500#2]
你定制好的USB我是不是能直接用，还是说要重新定制。

**Comment by jianyun8023** [comment]
确定是一样型号主板，能直接用的。

**Comment by hoowhoami** [comment]
> 确定是一样型号主板，能直接用的。

简直一模一样，今晚回家试试。
谢谢大佬的分享。

**Comment by jianyun8023** [comment]
不客气~祝顺利

**Comment by hoowhoami** [comment]
> 不客气~祝顺利

大佬，我这边安装好了，其它没啥问题，就这个键盘方向键右键貌似有问题，而且右边小键盘的0键一按就有提示音。。。
这个问题你有遇到过吗？

**Comment by jianyun8023** [comment]
> > 不客气~祝顺利
> 
> 大佬，我这边安装好了，其它没啥问题，就这个键盘方向键右键貌似有问题，而且右边小键盘的0键一按就有提示音。。。 这个问题你有遇到过吗？

键盘没设置对吧，在设置里重新识别下键位

**Comment by hoowhoami** [comment]
> > > 不客气~祝顺利
> > 
> > 
> > 大佬，我这边安装好了，其它没啥问题，就这个键盘方向键右键貌似有问题，而且右边小键盘的0键一按就有提示音。。。 这个问题你有遇到过吗？
> 
> 键盘没设置对吧，在设置里重新识别下键位

怀疑是键盘突然坏了，因为进windows也有一样的情况。京东买了个键盘，今晚再试试。

**Comment by hoowhoami** [comment]
就是键盘坏了，新键盘一切正常，也是醉了。
